%%

load icra17_final;
icra17_figures_8;
icra17_figures_9; % TODO redo this???
icra17_figures_10;

%%

bdata14 = containers.Map;
bdata38 = containers.Map;
for i = 1:length(materials)
    d = data14(materials{i});
    e = struct('pos', d.vei, ...
               'b_pos', d.bvei, ...
               'force', d.iws(:,1:4), ...
               'b_force', d.biws(:,1:4), ...
               'acc', d.ai, ...
               'b_acc', d.bai, ...
               'index', input(sprintf('index for 1/4in %s: ', materials{i})));
    bdata14(materials{i}) = e;
    
    d = data38(materials{i});
    e = struct('pos', d.vei, ...
               'b_pos', d.bvei, ...
               'force', d.iws(:,1:4), ...
               'b_force', d.biws(:,1:4), ...
               'acc', d.ai, ...
               'b_acc', d.bai, ...
               'index', input(sprintf('index for 3/8in %s: ', materials{i})));
    bdata38(materials{i}) = e;
end