function [v, int, acc] = load_stick(prefix)

    v = csvload([prefix 'vicon.tsv'], ...
                {'Timestamp', ...
                 'proton_Root_T_X_', 'proton_Root_T_Y_', 'proton_Root_T_Z_', ...
                 'proton_Root_A_X_', 'proton_Root_A_Y_', 'proton_Root_A_Z_'}, ...
                {'Delimiter', '\t'});

    int = csvload([prefix 'teensy.ft.csv'], ...
                  [{'Timestamp'}, ...
                   arrayfun(@(x) ['FT' num2str(x)], 0:11, 'UniformOutput',false)]);

    acc = csvload([prefix 'teensy.acc.csv'], ...
                  {'Timestamp', 'FIFOPosition', 'AccX', 'AccY', 'AccZ'});

    % unpack raw sensor data
    int = process_mini40(int);
    acc = unfifo(acc);

end
