function [v, int, dig_acc, dig_gyro, mic, ana_acc] = load_stick(prefix)

    v = csvload([prefix 'vicon.tsv'], ...
                {'Timestamp', ...
                 'proton_Root_T_X_', 'proton_Root_T_Y_', 'proton_Root_T_Z_', ...
                 'proton_Root_A_X_', 'proton_Root_A_Y_', 'proton_Root_A_Z_'}, ...
                {'Delimiter', '\t'});

    int = csvload([prefix 'teensy.ft.csv'], ...
                  [{'Timestamp'}, ...
                   arrayfun(@(x) ['FT' num2str(x)], 0:29, 'UniformOutput',false)]);

    acc = csvload([prefix 'teensy.acc.csv'], ...
                  {'Timestamp', 'FIFOPosition', 'AccX', 'AccY', 'AccZ'});
    gyro = csvload([prefix 'teensy.gyro.csv'], ...
                  {'Timestamp', 'FIFOPosition', 'GyroX', 'GyroY', 'GyroZ'});

    % unpack raw sensor data
    [int, mic, ana_acc] = process_mini40(int);
    dig_acc = unfifo(acc);
    dig_gyro = unfifo(gyro);

end
