% part 20 of /Users/alex/Documents/research/proton/code/calibration/motion/mfi16_figures.m
           %%
            fprintf('Processing data for %s on %s material, rep #%s\n', tools{ti}, materials{mi}, reps{ri});
            
            [vv{mi,ri,ti}, ii{mi,ri,ti}, ...
             vbody{mi,ri,ti}, vend{mi,ri,ti}, ...
             vint{mi,ri,ti}, vbodyint{mi,ri,ti}, vendint{mi,ri,ti}, ...
             accint{mi,ri,ti}, accworld{mi,ri,ti}, ...
             intbody{mi,ri,ti}, intworld{mi,ri,ti}, intworldsub{mi,ri,ti}] ...
                = process_stick(v{mi,ri,ti}, int{mi,ri,ti}, aacc{mi,ri,ti}, mass, com, H_vic2bod, H_m402bod, H_bal2imu, offset(ri));
